# Generated by Django 5.2.5 on 2026-02-10 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('requisitos_minimos', models.TextField()),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Juegos',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_suscripcion', models.CharField(choices=[('NORMAL', 'Normal'), ('PREMIUM', 'Premium'), ('VIP', 'VIP')], default='NORMAL', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('PENDIENTE_RENOVACION', 'Pendiente de Renovación'), ('CANCELADA', 'Cancelada'), ('EXPIRADA', 'Expirada')], default='ACTIVA', max_length=30)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_renovacion', models.DateTimeField()),
                ('notificacion_enviada', models.BooleanField(default=False)),
                ('cambios_mes_actual', models.IntegerField(default=0)),
                ('juegos_seleccionados', models.ManyToManyField(blank=True, related_name='suscripciones', to='suscripciones.juego')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Suscripciones',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('referencia', models.CharField(max_length=100, unique=True)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='suscripciones.suscripcion')),
            ],
            options={
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='HistorialCambioSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_anterior', models.CharField(choices=[('NORMAL', 'Normal'), ('PREMIUM', 'Premium'), ('VIP', 'VIP')], max_length=20)),
                ('tipo_nuevo', models.CharField(choices=[('NORMAL', 'Normal'), ('PREMIUM', 'Premium'), ('VIP', 'VIP')], max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='suscripciones.suscripcion')),
            ],
            options={
                'verbose_name_plural': 'Historial de Cambios',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
