# Generated by Django 5.2.5 on 2026-03-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_videojuego_alter_suscripcion_options_plan_creado_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='creado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
