# Generated by Django 5.2.14 on 2026-05-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_plan_creado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='requiere_suscripcion',
            field=models.BooleanField(default=True, help_text='Si esta activo, el usuario necesita suscripcion vigente para jugarlo'),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='slug_ejecutable',
            field=models.CharField(choices=[('snake', 'Snake'), ('tetris', 'Tetris'), ('pong', 'Pong'), ('breakout', 'Breakout')], default='snake', help_text='Identificador del motor de juego HTML5 a ejecutar', max_length=30),
        ),
    ]
